gmscompat: Don't use Context to get device-protected data directory
Not all packages have data directories:

FATAL EXCEPTION: AsyncTask #2
Process: system:ui, PID: 8982
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: No data directory found for package android
	at android.app.ContextImpl.getDataDir(ContextImpl.java:2560)
	at com.android.internal.gmscompat.dynamite.client.DynamiteContext.<init>(DynamiteContext.java:58)
	at com.android.internal.gmscompat.dynamite.GmsDynamiteHooks.getClientContext(GmsDynamiteHooks.java:64)
	at com.android.internal.gmscompat.dynamite.GmsDynamiteHooks.loadAssetsFromPath(GmsDynamiteHooks.java:93)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:143)
	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:374)
	at android.app.ResourcesManager.access$000(ResourcesManager.java:67)
	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:146)
	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:833)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:937)
	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2226)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1682)
	at com.android.internal.app.ResolverListAdapter$TargetPresentationGetter.getIconBitmap(ResolverListAdapter.java:920)
	at com.android.internal.app.ResolverListAdapter$ActivityInfoPresentationGetter.getIconBitmap(ResolverListAdapter.java:843)
	at com.android.internal.app.ResolverListAdapter$TargetPresentationGetter.getIcon(ResolverListAdapter.java:908)
	at com.android.internal.app.ResolverListAdapter$ActivityInfoPresentationGetter.getIcon(ResolverListAdapter.java:843)
	at com.android.internal.app.ResolverListAdapter.loadIconForResolveInfo(ResolverListAdapter.java:599)
	at com.android.internal.app.ResolverListAdapter$LoadIconTask.doInBackground(ResolverListAdapter.java:782)
	at com.android.internal.app.ResolverListAdapter$LoadIconTask.doInBackground(ResolverListAdapter.java:769)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

Use the underlying Environment methods instead to construct a
device-protected data path for GMs without relying on error-prone
Context methods.

Change-Id: I180cfe464f80a55ac534e150199ba1708841d13d